version: '3.6'

services:
  nginx:
    image: nginx:latest
    container_name: workstation-nginx-proxy
    ports:
      - '80:80'
      - '443:443'
      - '8929:8929' # GITLAB_EXTERNAL_PORT
    env_file: $NGINX_ENV_FILE
    volumes:
      - $NGINX_HOME_FOLDER/logs:/var/log/nginx/
      - $NGINX_HOME_FOLDER/loadenv.sh:/loadenv.sh:+x
      # SSL
      - $NGINX_HOME_FOLDER/ssl/server.crt:/etc/ssl/certs/$NGINX_SSL_FILE_BASE_NAME.crt
      - $NGINX_HOME_FOLDER/ssl/server.key:/etc/ssl/private/$NGINX_SSL_FILE_BASE_NAME.key
      # Templates
      - $NGINX_HOME_FOLDER/templates/global.template:/etc/nginx/templates/global.template
      - $NGINX_HOME_FOLDER/templates/portainer.template:/etc/nginx/templates/portainer.template
      - $NGINX_HOME_FOLDER/templates/gitlab.template:/etc/nginx/templates/gitlab.template
      - $NGINX_HOME_FOLDER/templates/nextcloud.template:/etc/nginx/templates/nextcloud.template
    command: ./loadenv.sh
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: workstation-portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - $PORTAINER_DOCKER_SOCKET:/var/run/docker.sock
      - $PORTAINER_HOME/data:/data
    restart: always

  bind9:
    image: ubuntu/bind9:latest
    container_name: workstation-bind9
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - $BIND9_HOME/loadenv.sh:/loadenv.sh
      - $BIND9_HOME/configuration:/etc/bind:rw
      - $BIND9_HOME/templates:/templates:rw
      - $BIND9_HOME/cache:/var/cache/bind:rw
    environment:
      - HOST_IP=$WORKSTATION_IP
      - DOMAIN=$WORKSTATION_DOMAIN
      - TZ=Europe/Paris
    command: ./loadenv.sh
    restart: always

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: workstation-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERPORT=$WIREGUARD_PORT
      - PEERS=$WIREGUARD_PEERS
      - PEERDNS=$BIND9_DOCKER_IP
    volumes:
      - $WIREGUARD_HOME/config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-server
    restart: always
    hostname: $GITLAB_EXTERNAL_HOST
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://$GITLAB_EXTERNAL_HOST:$GITLAB_EXTERNAL_PORT'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        listen_port = 80
        listen_https = false
    volumes:
      - $GITLAB_HOME/config:/etc/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/data:/var/opt/gitlab
    shm_size: 256m

  nextcloud-application:
    image: nextcloud:latest
    container_name: nextcloud-application
    restart: always
    links:
      - nextcloud-database
    volumes:
      - $NEXTCLOUD_HOME/application:/var/www/html
      - $NEXTCLOUD_HOME/config.php:/var/www/html/config/config.php
    environment:
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
      - MYSQL_HOST=nextcloud-database
      - TRUSTED_DOMAINS=$NEXTCLOUD_HOST
      - APPLICATION_HOST=$NEXTCLOUD_HOST
      - APPLICATION_SALT=$NEXTCLOUD_SALT
      - APPLICATION_SECRET=$NEXTCLOUD_SECRET

  nextcloud-database:
    image: mariadb:latest
    container_name: nextcloud-database
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - $NEXTCLOUD_HOME/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER